# Generated by Django 5.0.4 on 2024-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='rasm')),
                ('address', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
